version: '3.9'

services:
  csharpapp:
    container_name: csharpapp
    image: francescoxx/csharpapp:1.0
    build:
      context: ./csharp-crud-api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=recomendaciones;Username=postgres;Password=postgres"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: react-frontend
    build:
      context: ./Crud-Sencillo
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

volumes:
  pgdata: {}
